---
- hosts: messageQueue
  sudo: yes
  gather_facts: yes
  roles:
    - role: rabbitMQ
      rabbitMQ:
        users:
          - name: Jian
            password: chengdu
            tags: administrator